all:
  hosts:
    control_node: 
      ansible_host: 192.168.64.3
  children:
    servers:
      hosts:
        server1:
          ansible_host: 192.168.64.5
        server2:    
          ansible_host: 192.168.64.6
      vars:
        control_node_ip: 192.168.64.3
