all:
  hosts:
  children:
    servers:
      hosts:
# Used dynamic inv to setting hosts name and ips'
#        server1:
#          ansible_host: 192.168.64.5
#        server2:    
#          ansible_host: 192.168.64.6
    control_node:
      hosts:
        local:
    containers:
      hosts:
        ansible_container_test[1:3]:
      


