all:
  hosts:
    control_node: 
      ansible_host: 192.168.64.3
      ansible_user: greg
  children:
    servers:
      hosts:
        server1:
          ansible_host: 192.168.64.5
          ansible_user: greg  
        server2:    
          ansible_host: 192.168.64.6
          ansible_user: greg
      vars:
        control_node_ip: 192.168.64.3
