---
# tasks file for vsftpdRole
- name: Ensure `listen` and `listen_ipv6` are mutually exclusive
  ansible.builtin.assert:
    that: "vsftpd_listen != vsftpd_listen_ipv6"
  tags: vsftpd

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags: vsftpd

- name: Install Vsftpd
  ansible.builtin.package:
    name: '{{ vsftpd_packages }}'
    state: present
  tags: vsftpd

- name: Inlcude selinux.yml tasks
  ansible.builtin.include_tasks: selinux.yml
  when: ansible_selinux is defined and not ansible_selinux and ansible_selinux.status == 'enabled'

- name: Ensure `anon_root` exists
  ansible.builtin.file:
    path: '{{ vsftpd_anon_root }}'
    state: directory
    owner: '{{ vsftpd_owner }}'
    group: '{{ vsftpd_group }}'
    mode: '{{ vsftpd_mode }}'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_anon_root is defined
  tags: vsftpd

- name: Ensure `local_root` exists
  ansible.builtin.file:
    path: '{{ vsftpd_local_root }}'
    state: directory
    owner: '{{ vsftpd_owner }}'
    group: '{{ vsftpd_group }}'
    mode: '{{ vsftpd_mode }}'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_local_root is defined
  tags: vsftpd

- name: Install configuration file
  ansible.builtin.template:
    src: etc_vsftpd_vsftpd.conf.j2
    dest: "{{ vsftpd_config_file }}"
    mode: '0600'
   # validate: 'vsftpd -olisten=NO %s'
   # validation always exits with status 1, even if everything seems ok
  notify: restart vsftpd
  tags: vsftpd

- name: Add extra (ACL) permissions
  ansible.posix.acl:
    name: "{{ item.folder }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    state: present
  with_items: "{{ vsftpd_extra_permissions }}"
  when: vsftpd_extra_permissions is defined
  tags: vsftpd

- name: Ensure service is started
  ansible.builtin.service:
    name: '{{ vsftpd_service }}'
    state: started
    enabled: true
  tags: vsftpd
