---
# https://docs.ansible.com/ansible/2.9/modules/docker_container_module.html
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_image_module.html

- name: Make sure docker package is installed
  hosts: control_node
  become: true
  tasks:
  - name: Install docker package
    ansible.builtin.pip:
     name: docker
     state: present

  - name: Pull my own image
    community.docker.docker_image:
     name: gregvader98/backend-server:test1
     source: pull
    register: backend_result

  - name: Print the results for debug
    ansible.builtin.debug:
     msg:
      - " {{ backend_result }} "

  - name: Start a container with a command
    community.docker.docker_container:
     name: Commerce
     image: gregvader98/backend-server:test1
     command: bash
    when: backend_result.failed == 0

  - name: Pull python image
    community.docker.docker_image:
     name: python:latest
     source: pull
    register: python_result

  - name: Ensure python docker container started
    community.docker.docker_container:
     image: python
     # command: ["sleep", "infinity"]
     command: sleep 1d
     interactive: true
     name: "{{ item }}"
     state: started
    loop: "{{ query('inventory_hostnames', 'containers') }}"


- name: Ensure git configured in containers
  hosts: containers
  tasks:
   - name: List current git config
     community.general.git_config:
      scope: global
      list_all: true

   - name: List git config file
     community.general.git_config:
      scope: global
      list_all: true

   - name: Set user for git
     community.general.git_config:
      scope: global
      name: user.name
      value: greg

   - name: List git config file after changes
     community.general.git_config:
      scope: global
      list_all: true
