---
# ansible -m copy -a "src=../master.gitconfig dest=~/.gitconfig" localhost
# Playbook to play
- name: Ensure git is installed on hosts
  hosts: control_node servers
  become: true
  tasks:
  - name: Install latest git package
    ansible.builtin.yum:
     name: git
     state: latest
     update_only: false

- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: servers control_node
  become: true
  tasks:

   - name: Git_config module to list config
     community.general.git_config:
      list_all: true
      scope: global

   - name: Show config in targets
     ansible.builtin.command:
      cmd: git config --global --list
     ignore_errors: true
     register: git_config_before

   - name: Show git config
     ansible.builtin.debug:
      var: git_config_before

   - name: Copy and paste file
     ansible.builtin.copy:
      src: ../master.gitconfig
      dest: ~/.gitconfig
      mode: '644'

   - name: Show newly added config
     ansible.builtin.command:
      cmd: git config --global --list
     ignore_errors: true
     register: git_config_after

   - name: Ensure git config after with debug
     ansible.builtin.debug:
      var: git_config_after.stdout_lines

- name: Ensure packages are updated
  hosts: servers control_node
  become: true
  tasks:
   - name: Check for all packages
     ansible.builtin.yum:
      name: '*'
      state: latest
      exclude: any-package*
      bugfix: true
      update_only: true
