---
# https://github.com/bertvv/ansible-role-vsftpd/tree/vagrant-tests
# to test if vsftpd works run ftp localhost
- name: Test installing and configuring vsftpd service
  hosts: control_node
  become: true
  vars:
    vsftpd_anon_root: /srv/shares/public
    vsftpd_local_enable: true
    vsftpd_local_root: /srv/shares/private
    vsftpd_options:
      - key: delete_failed_uploads
        value: 'YES'
      - key: ftpd_banner
        value: 'Welcome to the FTP service'
  roles:
    - { role: ../roles/vsftpd }
  pre_tasks:
    - name: Check for ansible.builtin.debug var
      ansible.builtin.debug:
        var: ansible_python_interpreter
    - name: Check for ansible_os_family
      ansible.builtin.debug:
        var: ansible_os_family
  post_tasks:
    - name: Put a demo file in the anonymous directory
      ansible.builtin.copy:
        dest: '{{ vsftpd_anon_root }}/README'
        content: 'anon_root'
        mode: '0644'
    - name: Put a demo file in the user directory
      ansible.builtin.copy:
        dest: '{{ vsftpd_local_root }}/README'
        content: 'local_root'
        mode: '0644'
    - name: Add user for testing authenticated access
      ansible.builtin.user:
        name: greg
        state: present
        # python -c 'import crypt; print(crypt.crypt("nimda", "$1$SomeSalt$"))'
        password: $1$SomeSalt$8v5hnG33jKbUbUa33XRMs.
        generate_ssh_key: true
        ssh_key_type: 'ecdsa'
        ssh_key_file: '.ssh/id_ecdsa'
